### PR TITLE
Add support for parsing select result in Apache Arrow format

### PR DESCRIPTION
**Pull request by kou**
It's supported since Groonga 10.0.0.

### CODE REVIEW

**Comment by kou** [comment]
Should we test this with mock? Or should we communicate with real Groonga server?

**Comment by hhatto** [comment]
@kou 
wow!! Thanks for contribution.

> Should we test this with mock? Or should we communicate with real Groonga server?

Could you use mock?

**Comment by kou** [comment]
OK.
I'll work on this next year.

I want to talk about API to return result after test is ready.

Note: Apache Arrow support in Groonga is for high performance. If we convert Apache Arrow response to raw Python object (`list` of `dict`), it'll decrease performance. The current implementation does so for keeping the current API. I want to export `pyarrow.Table` directly to users for high performance but we need to consider a good API for it.

**Comment by kou** [comment]
I've added a test.

I want to talk about API.

Can we always return Apache Arrow object directly to users? Because users need high performance when users specify `output_type='apache-arrow'` explicitly.

Or should we return raw Python objects same as JSON output case by default? Should we return Apache Arrow object directory to use only if users specify an option to return Apache Arrow objects? (`poyonga.Groonga(prefer_apache_arrow=True)`?)

I prefer the former to the latter. The current implementation is the latter.

What do you think about the API?

**Comment by hhatto** [comment]
@kou
First of all, Thanks for your work.

> Can we always return Apache Arrow object directly to users?

I have two question about the above.

1. Is the Apache Arrow object that you want to return to the user the data without the metadata?
  Or do you mean the data without metadata like the table [in this process](https://github.com/hhatto/poyonga/pull/14/files#diff-841ddd847a06d97f83229114fd827cef7b4103ab39852e6fcefaf9f11b4dabb2R105) ?
  If you mean data including metadata, you can use raw data by referring to `Groonga[Select]Result().raw_data`.
2. I'm sorry I don't understand you very well. What is this *"always"* to?
  Does it mean to make `output_type='apache-arrow'` the default?

It would be very helpful if you could push the former code to another branch if possible, as I think it would be easier to understand with concrete code.

**Comment by kou** [comment]
Sorry for my less informative description.

>     1. Is the Apache Arrow object that you want to return to the user the data without the metadata?
>        Or do you mean the data without metadata like the table [in this process](https://github.com/hhatto/poyonga/pull/14/files#diff-841ddd847a06d97f83229114fd827cef7b4103ab39852e6fcefaf9f11b4dabb2R105) ?

The latter.

>        If you mean data including metadata, you can use raw data by referring to `Groonga[Select]Result().raw_data`.

I also don't want to convert the table into plain Python object. It's not effective when the table has many data.

>     2. I'm sorry I don't understand you very well. What is this _"always"_ to?
>        Does it mean to make `output_type='apache-arrow'` the default?

No. (Sorry...)
I wanted to say that `GroongaSelectResult.items` always returns the table instead of plain Python dict ONLY WHEN an user sends a request with `output_type='apache-arrow'`. If an user doesn't specify `output_type='apache-arrow'`, plain Python dict is returned  as always.

> It would be very helpful if you could push the former code to another branch if possible, as I think it would be easier to understand with concrete code.

Done: https://github.com/hhatto/poyonga/pull/15

I hope that it'll help you.

**Comment by hhatto** [comment]
Thank you.
I now understand the intent and benefits of the change.
I think the #15 method is better.

So, I have one additional question on Apache Arrow style processing.

I have committed an example here that supports the Apache Arrow format.
https://github.com/hhatto/poyonga/tree/kou-select-apache-arrow-direct-with-change-examples/examples/groonga_microblog_tutorial
(based on #15)

When I run it, the drilldown SELECT results are different between JSON format and Apache Arrow format.
Is this the intended behavior?

```
$ python 1_create.py
$ python 2_load.py
$ python 3_search_with_pyarrow.py
```

result of `3_search_with_pyarrow.py`:
```
[http with json response]
status: 0
item: 5
<class 'list'>
{'posted_by.name': 'hsiomaneki', 'comment': 'マイクロブログ作ってみました（甘栗むいちゃいました的な感じで）。', 'last_modified': 1268795100.0}
{'posted_by.name': 'グニャラくん', 'comment': '初の書き込み。テストテスト。', 'last_modified': 1268794800.0}
{'posted_by.name': 'hsiomaneki', 'comment': '@tasukuchan ようこそ!!!', 'last_modified': 1268795100.0}
{'posted_by.name': 'グニャラくん', 'comment': '@daijiro ありがとう！', 'last_modified': 1268798400.0}
{'posted_by.name': 'グニャラくん', 'comment': 'groongaなう #groonga', 'last_modified': 1268802000.0}

=*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*=

[http with apache arrow response]
status: 0
item: 2
<class 'pyarrow.lib.Table'>
pydict: {'_key': ['daijiro', 'tasukuchan'], '_nsubrecs': [2, 3]}
[
  [
    "daijiro",
    "tasukuchan"
  ]
]
[
  [
    2,
    3
  ]
]
```

**Comment by kou** [comment]
Groonga's Apache Arrow output doesn't support drilldowns yet.
I'll send a pull request to support drilldowns when Groonga supports it.

BTW, we need to use `command_version=3` to use Apache Arrow output.
I'll update #15 for it.

**Comment by kou** [comment]
Should we close this in favor of #15?

**Comment by hhatto** [comment]
> Groonga's Apache Arrow output doesn't support drilldowns yet.
I'll send a pull request to support drilldowns when Groonga supports it.

I see. By all means!

> BTW, we need to use command_version=3 to use Apache Arrow output.
I'll update #15 for it.

Thanks

> Should we close this in favor of #15?

I close this, and merge #15.

**Pull request closed without merging**
